export enum ActivityType {
  FLASH_CARDS = 'FLASH_CARDS',
  MATCH = 'MATCH',
  DRAG_AND_DROP = 'DRAG_AND_DROP',
  FILL_BLANK = 'FILL_BLANK',
  TRUE_FALSE = 'TRUE_FALSE',
  SENTENCE_BUILDER = 'SENTENCE_BUILDER',
  FIND_THE_MISTAKE = 'FIND_THE_MISTAKE',
}
