export enum LessonSectionType {
  HERO = 'HERO',
  OBJECTIVES = 'OBJECTIVES',
  INTRODUCTION = 'INTRODUCTION',
  EXPLANATION = 'EXPLANATION',
  EXAMPLES = 'EXAMPLES',
  INTERACTIVE_ACTIVITY = 'INTERACTIVE_ACTIVITY',
  KNOWLEDGE_CHECK = 'KNOWLEDGE_CHECK',
  SUMMARY = 'SUMMARY',
  COMPLETION = 'COMPLETION',
}
