export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  TRUE_FALSE = 'TRUE_FALSE',
  FILL_BLANK = 'FILL_BLANK',
  MATCH = 'MATCH',
  SENTENCE_BUILDER = 'SENTENCE_BUILDER',
  FIND_THE_MISTAKE = 'FIND_THE_MISTAKE',
}
